blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DiscusiÃ³n General
    url: https://github.com/JuanCarlosAcostaPeraba/WorkoutNow/discussions
    about: Para preguntas, ideas o discusiones generales
  - name: ğŸ“– DocumentaciÃ³n
    url: https://github.com/JuanCarlosAcostaPeraba/WorkoutNow/blob/main/README.md
    about: Consulta el README para informaciÃ³n sobre el proyecto
